Add support for Prime mice
flozz/rivalcfg pull request #169
Opened 2021-11-19 03:55 UTC by sephiroth99

This adds support for the SteelSeries Prime mice (#166).

Supported features:
- sensitivity
- led color
- led brightness
- polling rate

What is not supported:
- button mapping

By looking at the SSE3 database, it seems like the Prime and Prime+ support a new color handler. Instead, I was able to reuse the regular `color` handler by using the `command` and `command_suffix` fields to build a valid packet (but different from my captures). In short, the RGB color value is present twice in the data, at the start and at the end. Sending only at the start also works. But this means supporting the Prime+ will most likely require to correctly implement this new color handler.

There were a few changes to the core code, mainly:
- added support for variable size in the `range` handler (new option `range_length_byte`)
- added support for zero based indexing of the `multidpi_range` handler

2021-11-22 12:06 UTC, flozz commented
> added support for zero based indexing of the multidpi_range handler

Hum that's annoying, I have already an implementation for this in the [aerox3-wireless](https://github.com/flozz/rivalcfg/blob/aerox3-wireless/rivalcfg/handlers/multidpi_range.py#L45) branch... Maybe I can merge this part of the branch on `master` to allow you to use it in your PR?

Except this ↑ your PR looks great :)

2021-11-23 02:13 UTC, sephiroth99 commented
> > added support for zero based indexing of the multidpi_range handler
> 
> Hum that's annoying, I have already an implementation for this in the [aerox3-wireless](https://github.com/flozz/rivalcfg/blob/aerox3-wireless/rivalcfg/handlers/multidpi_range.py#L45) branch... Maybe I can merge this part of the branch on `master` to allow you to use it in your PR?
> 
> Except this ↑ your PR looks great :)

I had a look at the `first_preset` option and it seems fine to me. If you want to put that part now in `master`, I'll rebase on top of it, no problem for me.

2021-11-23 11:34 UTC, flozz commented
The updated `multidpi_range` is on `master` :)

2021-11-26 05:47 UTC, sephiroth99 commented
OK I updated the code to use the new `multidpi_range`, everything seem a-ok on my side! Let me know if there are any other issues.

2021-11-26 12:52 UTC, flozz requested changes
There is just a key to rename to be more consistent with other devices. Great job! :+1:

2021-11-26 12:52 UTC, flozz commented on rivalcfg/devices/prime.py
> +        "wheel_brightness": {
I think this should be renamed `led_brightness` to be consistent with other devices

2021-11-28 14:02 UTC, merged

2021-11-28 14:05 UTC, flozz commented
Thank you, the Prime support will be released in the next Rivalcfg version :)